language: go

go:
  - 1.3

script: 
  - go test ./... -v

before_script:
  - createuser -Srl Gabriel
  - psql -c 'create database Gabriel;' -U postgres
  - psql -c 'create database gomez_test;' -U Gabriel
